blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/RAY-Group-eu/JobBridge/discussions
    about: Für Fragen, Feedback und allgemeine Diskussionen.

  - name: Dokumentation
    url: https://www.jobbridge.app
    about: Offizielle Website und weiterführende Informationen.

  - name: Support & Kontakt
    url: mailto:mail@r-yalcin.de
    about: Bei offiziellen Anfragen oder privatem Feedback.
